#!/bin/sh

if [ $1 == "upgrade" ]; then
    docker pull -a wroge/wms
fi

if [ -z $VERSION ]; then
    VERSION+=":latest"
else 
    VERSION=":${VERSION}"
fi

docker run -v "$(pwd)/output:/output" wroge/wms$VERSION $@